[theme]
primaryColor = "#E1306C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 500
enableXsrfProtection = true
headless = false

[browser]
serverAddress = "localhost"
serverPort = 8502
